config/routes.rb
Rails.application.routes.draw do
  get '/customers/:id/orders', to: 'orders#customer_index', as: 'customer_orders'
  post "/customers/update_province", to: "customers#update_province", as: :update_province
  devise_for :customers
  get '/orders/invoice', to: 'orders#invoice', as: 'order_invoice'
  post '/invoice/submit', to: 'orders#submit_invoice', as: 'submit_invoice'
  get '/order_summary/:id', to: 'orders#summary', as: 'order_summary'
  post "/cart/:id/update_quantity", to: "cart#update_quantity", as: :update_quantity_cart
  get "/orders/create", to: "orders#create", as: "checkout_create"
  get "/orders/success", to: "orders#success", as: "checkout_success"
  get "/orders/cancel", to: "orders#cancel", as: "checkout_cancel"
  get 'search_by_category', to: 'search#search_by_category'
  get 'search_all', to: 'search#search_all', as: 'search_all'
  resources :pages, except: [ :show ]
  get "/pages/:permalink", to: "pages#permalink", as: "page_permalink"

  resources :cart, only: [:create, :destroy]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "home#index"
  resources :orders, only: [:new, :create]
  resources :customers
  resources :products
  resources :categories


  get "up" => "rails/health#show", as: :rails_health_check

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :order_details
  has_one_attached :image

  validates :name, uniqueness: true
  validates :name, :description, presence: true
  validates :stockquantity, numericality: { only_integer: true }
  validates :price, numericality: true

  def self.ransackable_attributes(auth_object = nil)
    ["category_id", "created_at", "description", "id", "id_value", "name", "price",
     "stockquantity", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["category", "order_details"]
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # Set the product before the show, edit, update and destroy actions
  before_action :set_product, only: %i[show edit update destroy]
  before_action :track_visit, only: [:show]

  # GET /products or /products.json
  def index
    @products = Product.includes(:category).order(name: :asc, created_at: :asc).page(params[:page]).per(20)
  end

  # GET /products/1 or /products/1.json
  def show
    @product = Product.find(params[:id])
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit; end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy!

    respond_to do |format|
      format.html do
        redirect_to products_path, status: :see_other, notice: "Product was successfully destroyed."
      end
      format.json { head :no_content }
    end
  end

  # Tracking Product Sessions Logic Section
  def track_visit
    session[:visit] ||= 0
    session[:visit] += 1

    flash[:notice] = "You've visited #{session[:visit]} products!"
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params.expect(:id))
  end

  # Only allow a list of trusted parameters through.
  def product_params
    params.expect(product: %i[name description price stockquantity category_id])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :stockquantity, style: "display: block" %>
    <%= form.number_field :stockquantity %>
  </div>

  <div>
    <%= form.label :category_id, style: "display: block" %>
    <%= form.text_field :category_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">

  </head>

  <body>
    <div class="mb-4">
      <%= link_to "Back to Products", products_path, class: "button is-link" %>
    </div>
    <section class="section mt-0">
      <div class="container">

        <!-- Display the Products in a "Card" view -->
        <div class="card product-card">
          <% if @product.image.attached? %>
            <div class="card-image">
              <div class="columns is-centered">
                <div class="column is-half">
                  <figure class="image is-square">
                    <%= image_tag @product.image %>
                  </figure>
                </div>
              </div>
            </div>
          <% end %>

          <div class="card-content">
            <div class="content">

              <!-- Display Product Information -->
              <p>
                <h2 class="title is-4 mt-6">Name:</h2>
                <%= @product.name %>
              </p>

              <p>
                <h2 class="title is-4 mt-6">Description:</h2>
                <%= @product.description %>
              </p>

              <p>
                <h2 class="title is-4 mt-6">Price:</h2>
                $<%= @product.price %>
              </p>

              <p>
                <h2 class="title is-4 mt-6">Stock Quantity:</h2>
                <%= @product.stockquantity %>
              </p>

              <p>
                <h2 class="title is-4 mt-6">Category:</h2>
                <%= link_to @product.category.name, category_path(@product.category), class: "has-text-link" %>
              </p>

              <!-- Add or Remove the Product from the Cart -->
              <div class="mt-4">
                <% if cart.include?(@product) %>
                  <%= button_to cart_path(@product), method: :delete, class: "button is-small is-danger" do %>
                    Remove from Cart
                  <% end %>
                <% else %>
                  <%= form_with url: cart_index_path, method: :post do %>
                    <%= hidden_field_tag :id, @product.id %>
                    <div class="field">
                      <label class="label">Quantity</label>
                      <div class="control">
                        <%= number_field_tag :quantity, 1, min: 1, max: @product.stockquantity, class: "input" %>
                      </div>
                    </div>
                    <%= button_tag "Add to Cart", class: "button is-primary" %>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </body>
</html>

app/views/products/edit.html.erb
<% content_for :title, "Editing product" %>

<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>All Products</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
  </head>

  <body>
    <section class="section">
      <div class="container">
        <!-- Bulma Flash notifications -->
        <% flash.each do |type, msg| %>
          <% bulma_class = case type.to_sym
                           when :notice then "is-success"
                           when :alert then "is-danger"
                           else "is-info"
                           end %>
          <div class="notification <%= bulma_class %>">
            <%= msg %>
          </div>
        <% end %>

        <h1 class="title is-2">All Products</h1>

        <ol class="ml-5">
          <% @products.each do |product| %>
            <li class="mb-5 box">
              <div class="columns is-vcentered">
                <div class="column is-one-third">
                  <% if product.image.attached? %>
                    <%= image_tag product.image, class: "image is-128x128" %>
                  <% else %>
                    <p class="has-text-grey-light">No image available</p>
                  <% end %>
                </div>

                <div class="column">
                  <p class="title is-5 mb-1">
                    <%= link_to product.name, product %>
                  </p>
                  <p class="subtitle is-6">
                    <em>(<%= link_to product.category.name, product.category %>)</em>
                  </p>
                  <p class="content mb-2 has-text-grey-dark">
                    <%= product.description %>
                  </p>
                  <p class="has-text-weight-semibold mt-2">
                    In Stock: <span class="has-text-success"><%= product.stockquantity %></span>
                  </p>
                </div>
              </div>
            </li>
          <% end %>
        </ol>

        <div class="mt-4">
          <%= paginate @products %>
        </div>
      </div>
    </section>
  </body>
</html>

app/views/products/new.html.erb
<% content_for :title, "New product" %>

<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>