config/routes.rb
Rails.application.routes.draw do
  get '/customers/:id/orders', to: 'orders#customer_index', as: 'customer_orders'
  post "/customers/update_province", to: "customers#update_province", as: :update_province
  devise_for :customers
  get '/orders/invoice', to: 'orders#invoice', as: 'order_invoice'
  post '/invoice/submit', to: 'orders#submit_invoice', as: 'submit_invoice'
  get '/order_summary/:id', to: 'orders#summary', as: 'order_summary'
  post "/cart/:id/update_quantity", to: "cart#update_quantity", as: :update_quantity_cart
  get "/orders/create", to: "orders#create", as: "checkout_create"
  get "/orders/success", to: "orders#success", as: "checkout_success"
  get "/orders/cancel", to: "orders#cancel", as: "checkout_cancel"
  get 'search_by_category', to: 'search#search_by_category'
  get 'search_all', to: 'search#search_all', as: 'search_all'
  resources :pages, except: [ :show ]
  get "/pages/:permalink", to: "pages#permalink", as: "page_permalink"

  resources :cart, only: [:create, :destroy]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "home#index"
  resources :orders, only: [:new, :create]
  resources :customers
  resources :products
  resources :categories


  get "up" => "rails/health#show", as: :rails_health_check

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_one_attached :image
  validates :name, uniqueness: true
  validates :name, :description, presence: true

  has_many :products

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "description", "id", "id_value", "name", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["products"]
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, presence: true, uniqueness: { case_sensitive: false }

  # belongs_to :province

  has_many :orders
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer

  validates :total, numericality: true

  has_many :order_details
  has_many :products, through: :order_details
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :product

  validates :quantity, numericality: { only_integer: true }
  validates :price_at_purchase, :total, numericality: true
  validates :quantity, :price_at_purchase, :total, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "order_id", "price_at_purchase", "product_id", "quantity", "updated_at"]
  end
end

app/models/page.rb
class Page < ApplicationRecord
  validates :title, :content, :permalink, presence: true
  validates :permalink, uniqueness: true

  def self.ransackable_attributes(auth_object = nil)
    ["content", "created_at", "id", "id_value", "permalink", "title", "updated_at"]
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :order_details
  has_one_attached :image

  validates :name, uniqueness: true
  validates :name, :description, presence: true
  validates :stockquantity, numericality: { only_integer: true }
  validates :price, numericality: true

  def self.ransackable_attributes(auth_object = nil)
    ["category_id", "created_at", "description", "id", "id_value", "name", "price",
     "stockquantity", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["category", "order_details"]
  end
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
  belongs_to :product

  validates :imageurl, uniqueness: true
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :customers
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  # Set the cart before the create and destroy actions
  before_action :get_product, only: %i[create destroy]

  # to_i is used to convert from parameters string to int
  def create
    # Get the product id
    product_id = params[:id].to_i
    # Get the product quantity
    quantity = params[:quantity].to_i

    # Find the existing item in the cart with the same product id
    existing_item = session[:cart].find do |item|
      item_id = item["id"]
      item_id == product_id
    end

    # If the Item is already in the Cart update the Product Quantity and display a message to the User
    if existing_item
      existing_item["quantity"] += quantity
      flash[:notice] =
        "#{quantity}x #{@product.name} were added to your cart! Total quantity: #{existing_item['quantity']}."
    else
      # If the Item is not in the Cart, add it and display a message to the User
      session[:cart] += [{ "id" => product_id, "quantity" => quantity }]
      flash[:notice] = "#{quantity}x #{@product.name} were added to the cart!"
    end
    redirect_to root_path
  end

  def destroy
    # Get the product
    product_id = params[:id].to_i
    # If the product Id matches, remove the product from the current cart session
    session[:cart].delete_if do |item|
      item_id = item["id"]
      item_id == product_id
    end
    # Display a message to the user that the item wasremoved
    flash[:notice] = "#{@product.name} was removed from the cart!"
    redirect_to root_path
  end

  # Cart Quantity Update Logic Section
  def update_quantity
    # Get the Product
    product = Product.find(params[:id])
    # Get the current quantity
    new_quantity = params[:quantity].to_i

    # Validate that the quantity is more than 0
    if new_quantity.positive?
      # Initialize the cart session if it was not created already
      session[:cart] ||= []
      # Find the item with the matching product item
      item = session[:cart].find do |i|
        i["id"] == product.id
      end
      # If Item exists, update the quantity
      item["quantity"] = new_quantity if item
      # Display a message telling the user the quantity was updated
      flash[:notice] = "#{product.name} quantity updated."
    else
      # Display a message telling the user that they need a quantity of at least 1
      flash[:alert] = "Quantity must be at least 1."
    end
    redirect_to root_path
  end

  def checkout; end

  private

  # Cart Get Product Update Logic Section
  def get_product
    product_id = params[:id].to_i
    @product = Product.find(product_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/common/_footer.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bulma CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
  </head>

    <footer>

        <ul class="menu is-inline ">
          <li class="menu-item"><%= link_to "Home", root_path %></li>
          <li class="menu-item"><%= link_to "Products", products_path %></li>
          <li class="menu-item"><%= link_to "Categories", categories_path %></li>
        </ul>
        <p class="mt-2">&copy; <%= Time.now.year %> Evolve Athletics. All Rights Reserved.</p>

    </footer>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:html_title) || "EvolveAthletics" %></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
  </head>

  <body>
    <header>
      <nav class="navbar is-light" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
          <a class="navbar-item" href="/">
            <strong>Evolve Athletics</strong>
          </a>
        </div>

        <!-- Search Bar Query Section-->
        <%= form_with url: search_all_path, method: :get, local: true do |form| %>
          <div class="field has-addons">
            <div class="control">
              <%= form.text_field :query, placeholder: "Search for Products or Categories...", class: "input" %>
            </div>
            <!-- options_from_collection_for_selection: Options for the Dropdown Menu-->
            <div class="control">
              <%= form.select :category_id,
                options_from_collection_for_select(@all_categories, :id, :name),
                { include_blank: "Pick a Category..." },
                class: "input" %>
            </div>
            <div class="control">
              <%= form.submit "Search", class: "button is-primary" %>
            </div>
          </div>
        <% end %>

        <div class="buttons mt-2 ml-2">
          <%= link_to "All Products", products_path, class: "button is-info is-small" %>
          <%= link_to "All Categories", categories_path, class: "button is-info is-small" %>
        </div>

        <div class="navbar-menu">
          <div class="navbar-end">
            <div class="navbar-item">
              <div class="field is-grouped">
                <p class="control">
                  <%= button_to "About Us", page_permalink_path("about"), method: :get, class: "button is-small is-link" %>
                </p>
                <p class="control">
                  <%= button_to "Contact", page_permalink_path("contact"), method: :get, class: "button is-small is-link" %>
                </p>
                <p class="control">
                  <%= button_to "Admin", new_admin_user_session_path, method: :get, class: "button is-small is-link" %>
                </p>
                <!-- Checks to see if the Customer is logged in, and displays links based on it-->
                <% if customer_signed_in? %>
                  <p class="control">
                    <%= link_to "My Account", edit_customer_registration_path, class: "button is-small is-success" %>
                  </p>
                  <p class="control">
                    <%= button_to "Sign Out", destroy_customer_session_path, method: :delete %>
                  </p>
                <% else %>
                  <p class="control">
                    <%= link_to "Login", new_customer_session_path, class: "button is-small is-link" %>
                  </p>
                <% end %>
              </div>
            </div>

            <div class="navbar-item has-dropdown is-hoverable">
              <a class="navbar-link">
                🛒 Cart<%= " (#{cart.size})" if cart.present? %>
              </a>

              <% if cart.present? %>
                <div class="navbar-dropdown is-right">
                  <% cart.each do |item| %>
                    <div class="navbar-item is-flex is-justify-content-space-between is-align-items-center">
                      <%= form_with url: update_quantity_cart_path(item[:product]), method: :post, local: true do |f| %>
                        <div class="field is-grouped">
                          <span class="mr-2">
                            <%= item[:product].name %>
                          </span>
                          <div class="control">
                            <%= f.number_field :quantity, value: item[:quantity], min: 1, class: "input is-small", style: "width: 60px;" %>
                          </div>
                          <div class="control">
                            <%= f.submit "Update", class: "button is-small is-info ml-2" %>
                          </div>
                        </div>
                      <% end %>
                      <%= button_to "Remove", cart_path(item[:product]), method: :delete, class: "button is-small is-danger ml-2" %>
                    </div>
                  <% end %>

                  <hr class="navbar-divider">

                  <div class="navbar-item">
                    <%= link_to "Invoice", order_invoice_path, class: "button is-primary" %>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </nav>
    </header>
    <section class="section">
      <div class="container">
        <!-- Bulma Flash notifications -->
        <% flash.each do |type, msg| %>
          <% bulma_class = case type.to_sym
            when :notice then "is-success"
            when :alert then "is-danger"
            else "is-info"
          end %>
          <div class="notification <%= bulma_class %>">
            <%= msg %>
          </div>
        <% end %>

        <!-- Render the Footer-->
        <%= yield %>
        <%= render partial: "common/footer" %>
      </div>
    </section>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_with(model: page) do |form| %>
  <% if page.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
        <% page.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.textarea :content %>
  </div>

  <div>
    <%= form.label :permalink, style: "display: block" %>
    <%= form.text_field :permalink %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pages/_page.html.erb
<div id="<%= dom_id page %>">
  <p>
    <strong>Title:</strong>
    <%= page.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= page.content %>
  </p>

  <p>
    <strong>Permalink:</strong>
    <%= page.permalink %>
  </p>

</div>

app/views/pages/edit.html.erb
<% content_for :title, "Editing page" %>

<h1>Editing page</h1>

<%= render "form", page: @page %>

<br>

<div>
  <%= link_to "Show this page", @page %> |
  <%= link_to "Back to pages", pages_path %>
</div>

app/views/pages/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Pages" %>

<h1>Pages</h1>

<div id="pages">
  <% @pages.each do |page| %>
    <%= render page %>
    <p>
      <%= link_to "Show this page", page %>
    </p>
  <% end %>
</div>

<%= link_to "New page", new_page_path %>

app/views/pages/new.html.erb
<% content_for :title, "New page" %>

<h1>New page</h1>

<%= render "form", page: @page %>

<br>

<div>
  <%= link_to "Back to pages", pages_path %>
</div>

app/views/pages/permalink.html.erb
<% content_for(:html_title) { @page.title } %>

<h2 class="title is-2"><%= @page.title%></h2>
<p><%= @page.content %></p>

app/views/pages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @page %>

<div>
  <%= link_to "Edit this page", edit_page_path(@page) %> |
  <%= link_to "Back to pages", pages_path %>

  <%= button_to "Destroy this page", @page, method: :delete %>
</div>